import React from 'react'
import PropTypes from 'prop-types'
import classNames from 'classnames'
import './style.scss'

// Icons
import { ReactComponent as Cart } from 'images/icon-cart.svg'
import { ReactComponent as Delete } from 'images/icon-delete.svg'

/* 
    NOTE: This isnt how I would implement this in a production scenario.
    If the ask were to write production ready code, I would ditch this 
    implementation in favor of one that uses an SVG Sprite generated by
    webpack.
*/

const validIcons = ['cart', 'delete']

const Icon = ({ glyph, className, ...rest }) => {
  let I

  switch (glyph) {
    case 'cart':
      I = Cart
      break
    case 'delete':
      I = Delete
      break
    default:
      /* 
        Lets provide a good developer experience and let the developer know 
        that something isnt quite right. I could write a custom proptype,
        but this is the "cheap" way to do it.
     */
      console.error(
        `\`${glyph}\` is not a valid glyph for Icon. Please try any one of the following: ${validIcons.join(
          ', '
        )}`
      )
      break
  }

  const classes = classNames({
    icon: true,
    [`${className}`]: className
  })
  return <I className={classes} {...rest} />
}

Icon.propTypes = {
  glyph: PropTypes.oneOf(validIcons).isRequired
}

export default Icon
